# Project name
name: socialdeck

# Short project description
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Dart SDK environment
environment:
  sdk: ^3.7.2

#---------------------- Dependencies ---------------------#
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  go_router: ^15.1.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  intl: ^0.20.2
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.3.4
  google_sign_in: ^6.2.1
  dotted_border: 2.1.0
  image_picker: ^1.0.7
  crop_your_image: ^2.0.0
  flutter_image_compress: ^2.1.0
  shared_preferences: ^2.2.2
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.6
  photo_manager: ^3.2.0
  permission_handler: ^11.3.1
  

# Development-only dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15

#---------------------- Packages --------------------#
flutter:
  uses-material-design: true

  #-------------------- ASSETS -----------------------#
  assets:
    # Icons - Monochrome
    - assets/icons/stroke/
    - assets/icons/fill/
    - assets/icons/misc/
    # Background Patterns
    - assets/backgrounds/
    # Fonts
    - assets/fonts/
    # Splash Screen
    - assets/splash_screen/
    # Photos
    - assets/Photos/


  #-------------------- FONTS -----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
