# Project name
name: socialdeck

# Short project description
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Dart SDK environment
environment:
  sdk: ^3.7.2

#---------------------- Dependencies ---------------------#
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10

# Development-only dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#---------------------- Packages --------------------#
flutter:
  uses-material-design: true

  #-------------------- ASSETS -----------------------#
  assets:
    - assets/icons/defaultStroke/
    - assets/icons/defaultFill/
    - assets/icons/invertedStroke/
    - assets/icons/miscellaneous/
    - assets/fonts/

  #-------------------- FONTS -----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
